import React, { useEffect, useRef, useState } from 'react';
import { renderAsync } from 'docx-preview';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Loader2, X, Download, FileText, AlertTriangle } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface WordDocumentViewerProps {
  fileUrl: string;
  fileName?: string;
  onClose?: () => void;
  className?: string;
  height?: string;
}

export const WordDocumentViewer: React.FC<WordDocumentViewerProps> = ({
  fileUrl,
  fileName = 'Document',
  onClose,
  className = '',
  height = '600px'
}) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const { toast } = useToast();

  useEffect(() => {
    const loadDocument = async () => {
      if (!containerRef.current || !fileUrl) return;

      setIsLoading(true);
      setError(null);

      try {
        // Clear previous content
        containerRef.current.innerHTML = '';

        // Fetch the document with proper authentication
        const token = localStorage.getItem("jwtToken");
        const response = await fetch(fileUrl, {
          credentials: 'include',
          headers: {
            'Accept': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/html,*/*',
            ...(token ? { 'Authorization': `Bearer ${token}` } : {})
          }
        });

        if (!response.ok) {
          throw new Error(`Failed to load document: ${response.status} ${response.statusText}`);
        }

        const contentType = response.headers.get('content-type');
        
        // Handle HTML reports generated by our system
        if (contentType && contentType.includes('text/html')) {
          let htmlContent = await response.text();
          
          // Clean up unwanted header and footer sections from existing reports
          htmlContent = htmlContent
            // Remove header section with Generated on
            .replace(/<div class="header">[\s\S]*?<\/div>/gi, '')
            // Remove signature section with Generated by
            .replace(/<div class="signature">[\s\S]*?<\/div>/gi, '')
            // Remove any standalone Generated on/by paragraphs
            .replace(/<p><strong>Generated on:.*?<\/p>/gi, '')
            .replace(/<p><strong>Generated by:.*?<\/p>/gi, '')
            .replace(/<p><strong>Date:.*?<\/p>/gi, '')
            .replace(/<p><strong>Time:.*?<\/p>/gi, '');
          
          // Add professional medical document styling to match the structured format
          const styledContent = `
            <div style="
              background: white; 
              padding: 40px; 
              font-family: 'Times New Roman', serif; 
              line-height: 1.6; 
              max-width: 800px; 
              margin: 0 auto; 
              box-shadow: 0 0 10px rgba(0,0,0,0.1);
              border: 1px solid #ddd;
              font-size: 12pt;
            ">
              <style>
                .patient-info-header { margin-bottom: 15px; }
                .patient-header-table { 
                  width: 100%; 
                  border-collapse: collapse; 
                  font-size: 12pt; 
                  margin-bottom: 20px;
                }
                .patient-header-table td { 
                  padding: 4px 8px; 
                  border: 1px solid #000; 
                  vertical-align: top; 
                }
                .patient-header-table .label { 
                  font-weight: bold; 
                  background-color: #f0f0f0; 
                  width: 30%; 
                }
                .patient-header-table .value { 
                  background-color: white; 
                }
                .content-section {
                  margin-bottom: 20px;
                }
                .signature-section {
                  margin-top: 40px;
                  border-top: 1px solid #ccc;
                  padding-top: 20px;
                }
              </style>
              ${htmlContent}
            </div>
          `;
          
          containerRef.current.innerHTML = styledContent;
          setIsLoading(false);
          return;
        }

        // Handle Word documents
        const arrayBuffer = await response.arrayBuffer();

        // First, try to detect if this is HTML content by examining the raw data
        const textContent = new TextDecoder().decode(arrayBuffer);
        
        // Check if content is HTML (our generated reports)
        if (textContent.includes('<html') || textContent.includes('<!DOCTYPE') || textContent.includes('<body')) {
          // Clean up unwanted header and footer sections from existing reports
          let cleanedContent = textContent
            // Remove header section with Generated on
            .replace(/<div class="header">[\s\S]*?<\/div>/gi, '')
            // Remove signature section with Generated by
            .replace(/<div class="signature">[\s\S]*?<\/div>/gi, '')
            // Remove any standalone Generated on/by paragraphs
            .replace(/<p><strong>Generated on:.*?<\/p>/gi, '')
            .replace(/<p><strong>Generated by:.*?<\/p>/gi, '')
            .replace(/<p><strong>Date:.*?<\/p>/gi, '')
            .replace(/<p><strong>Time:.*?<\/p>/gi, '');
          
          // It's HTML content - style it appropriately with medical document formatting
          const styledContent = `
            <div style="
              background: white; 
              padding: 40px; 
              font-family: 'Times New Roman', serif; 
              line-height: 1.6; 
              max-width: 800px; 
              margin: 0 auto; 
              box-shadow: 0 0 10px rgba(0,0,0,0.1);
              border: 1px solid #ddd;
              font-size: 12pt;
            ">
              <style>
                .patient-info-header { margin-bottom: 15px; }
                .patient-header-table { 
                  width: 100%; 
                  border-collapse: collapse; 
                  font-size: 12pt; 
                  margin-bottom: 20px;
                }
                .patient-header-table td { 
                  padding: 4px 8px; 
                  border: 1px solid #000; 
                  vertical-align: top; 
                }
                .patient-header-table .label { 
                  font-weight: bold; 
                  background-color: #f0f0f0; 
                  width: 30%; 
                }
                .patient-header-table .value { 
                  background-color: white; 
                }
                .content-section {
                  margin-bottom: 20px;
                }
                .signature-section {
                  margin-top: 40px;
                  border-top: 1px solid #ccc;
                  padding-top: 20px;
                }
              </style>
              ${textContent}
            </div>
          `;
          containerRef.current.innerHTML = styledContent;
          setIsLoading(false);
          return;
        }

        // Check if the response is actually a Word document by content type and file signature
        const isWordDoc = contentType && (
          contentType.includes('application/vnd.openxmlformats-officedocument.wordprocessingml.document') || 
          contentType.includes('application/octet-stream')
        );

        // Also check file signature (ZIP file magic bytes: PK)
        const uint8Array = new Uint8Array(arrayBuffer);
        const hasZipSignature = uint8Array[0] === 0x50 && uint8Array[1] === 0x4B; // "PK"

        if (!isWordDoc && !hasZipSignature) {
          // If it's not a Word document and doesn't have ZIP signature, treat as HTML with medical formatting
          const styledContent = `
            <div style="
              background: white; 
              padding: 40px; 
              font-family: 'Times New Roman', serif; 
              line-height: 1.6; 
              max-width: 800px; 
              margin: 0 auto; 
              box-shadow: 0 0 10px rgba(0,0,0,0.1);
              border: 1px solid #ddd;
              font-size: 12pt;
            ">
              <style>
                .patient-info-header { margin-bottom: 15px; }
                .patient-header-table { 
                  width: 100%; 
                  border-collapse: collapse; 
                  font-size: 12pt; 
                  margin-bottom: 20px;
                }
                .patient-header-table td { 
                  padding: 4px 8px; 
                  border: 1px solid #000; 
                  vertical-align: top; 
                }
                .patient-header-table .label { 
                  font-weight: bold; 
                  background-color: #f0f0f0; 
                  width: 30%; 
                }
                .patient-header-table .value { 
                  background-color: white; 
                }
                .content-section {
                  margin-bottom: 20px;
                }
                .signature-section {
                  margin-top: 40px;
                  border-top: 1px solid #ccc;
                  padding-top: 20px;
                }
              </style>
              ${textContent}
            </div>
          `;
          containerRef.current.innerHTML = styledContent;
          setIsLoading(false);
          return;
        }

        // Try to render as Word document using docx-preview
        try {
          await renderAsync(arrayBuffer, containerRef.current, undefined, {
            className: 'docx-preview-container',
            inWrapper: true,
            ignoreWidth: false,
            ignoreHeight: false,
            ignoreFonts: false,
            breakPages: true,
            ignoreLastRenderedPageBreak: false,
            experimental: false,
            trimXmlDeclaration: true,
            useBase64URL: false,
            useMathMLPolyfill: true,
            showChanges: false,
            debug: false
          });
        } catch (docxError) {
          console.warn('Failed to render as Word document, falling back to HTML:', docxError);
          
          // Fallback to HTML rendering with medical document formatting if docx parsing fails
          const styledContent = `
            <div style="
              background: white; 
              padding: 40px; 
              font-family: 'Times New Roman', serif; 
              line-height: 1.6; 
              max-width: 800px; 
              margin: 0 auto; 
              box-shadow: 0 0 10px rgba(0,0,0,0.1);
              border: 1px solid #ddd;
              font-size: 12pt;
            ">
              <style>
                .patient-info-header { margin-bottom: 15px; }
                .patient-header-table { 
                  width: 100%; 
                  border-collapse: collapse; 
                  font-size: 12pt; 
                  margin-bottom: 20px;
                }
                .patient-header-table td { 
                  padding: 4px 8px; 
                  border: 1px solid #000; 
                  vertical-align: top; 
                }
                .patient-header-table .label { 
                  font-weight: bold; 
                  background-color: #f0f0f0; 
                  width: 30%; 
                }
                .patient-header-table .value { 
                  background-color: white; 
                }
                .content-section {
                  margin-bottom: 20px;
                }
                .signature-section {
                  margin-top: 40px;
                  border-top: 1px solid #ccc;
                  padding-top: 20px;
                }
              </style>
              ${textContent}
            </div>
          `;
          containerRef.current.innerHTML = styledContent;
        }

        setIsLoading(false);
      } catch (err) {
        console.error('Error loading document:', err);
        const errorMessage = err instanceof Error ? err.message : 'Failed to load document';
        
        // Check if it's the ZIP file error and provide better feedback
        if (errorMessage.includes("Can't find end of central directory") || errorMessage.includes("zip file")) {
          setError('This appears to be a generated report in HTML format. The document viewer will display it accordingly.');
          
          // Try one more fallback - load as plain text and display
          try {
            const fallbackResponse = await fetch(fileUrl, {
              credentials: 'include',
              headers: {
                'Accept': 'text/plain,text/html,*/*',
                ...(typeof window !== 'undefined' && localStorage.getItem("jwtToken") ? { 'Authorization': `Bearer ${localStorage.getItem("jwtToken")}` } : {})
              }
            });
            
            if (fallbackResponse.ok) {
              const htmlContent = await fallbackResponse.text();
              const styledContent = `
                <div style="
                  background: white; 
                  padding: 40px; 
                  font-family: 'Times New Roman', serif; 
                  line-height: 1.6; 
                  max-width: 800px; 
                  margin: 0 auto; 
                  box-shadow: 0 0 10px rgba(0,0,0,0.1);
                  border: 1px solid #ddd;
                  font-size: 12pt;
                ">
                  <style>
                    .patient-info-header { margin-bottom: 15px; }
                .patient-header-table { 
                      width: 100%; 
                      border-collapse: collapse; 
                      font-size: 12pt; 
                      margin-bottom: 20px;
                    }
                    .patient-header-table td { 
                      padding: 4px 8px; 
                      border: 1px solid #000; 
                      vertical-align: top; 
                    }
                    .patient-header-table .label { 
                      font-weight: bold; 
                      background-color: #f0f0f0; 
                      width: 30%; 
                    }
                    .patient-header-table .value { 
                      background-color: white; 
                    }
                    .content-section {
                      margin-bottom: 20px;
                    }
                    .signature-section {
                      margin-top: 40px;
                      border-top: 1px solid #ccc;
                      padding-top: 20px;
                    }
                  </style>
                  ${htmlContent}
                </div>
              `;
              containerRef.current.innerHTML = styledContent;
              setIsLoading(false);
              setError(null);
              return;
            }
          } catch (fallbackError) {
            console.warn('Fallback loading also failed:', fallbackError);
          }
        } else {
          setError(errorMessage);
        }
        
        setIsLoading(false);
        
        toast({
          title: "Document Load Error",
          description: errorMessage.includes("zip file") 
            ? "Loading generated report in HTML format..." 
            : errorMessage,
          variant: errorMessage.includes("zip file") ? "default" : "destructive",
        });
      }
    };

    loadDocument();
  }, [fileUrl, toast]);

  const handleDownload = async () => {
    try {
      const token = localStorage.getItem("jwtToken");
      const response = await fetch(fileUrl, {
        credentials: 'include',
        headers: {
          ...(token ? { 'Authorization': `Bearer ${token}` } : {})
        }
      });
      
      if (!response.ok) {
        throw new Error('Failed to download document');
      }

      const contentType = response.headers.get('content-type');
      let blob = await response.blob();
      let downloadFileName = fileName.endsWith('.docx') ? fileName : `${fileName}.docx`;
      
      // If it's HTML content, convert it to a proper format for download
      if (contentType && contentType.includes('text/html')) {
        // Get a fresh response for HTML content
        const freshResponse = await fetch(fileUrl, {
          credentials: 'include',
          headers: {
            'Accept': 'text/html,*/*',
            ...(typeof window !== 'undefined' && localStorage.getItem("jwtToken") ? { 'Authorization': `Bearer ${localStorage.getItem("jwtToken")}` } : {})
          }
        });
        
        if (!freshResponse.ok) {
          throw new Error('Failed to fetch HTML content');
        }
        
        const htmlContent = await freshResponse.text();
        
        // Create a more complete HTML document for better Word compatibility
        const completeHtmlDoc = `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta charset="utf-8">
<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Medical Report System">
<title>${fileName}</title>
<style>
@page {
  size: 8.5in 11in;
  margin: 1in 1.25in 1in 1.25in;
}
body {
  font-family: 'Times New Roman', serif;
  font-size: 12pt;
  line-height: 1.15;
  margin: 0;
  background: white;
}
.header { text-align: center; margin-bottom: 30px; }
.patient-info-header { margin-bottom: 30px; border: 2px solid #000; }
.patient-info { margin-bottom: 20px; }
.content { margin-bottom: 20px; }
.signature { margin-top: 40px; }
h1 { color: #2c3e50; font-size: 18pt; font-weight: bold; }
h2 { font-size: 14pt; font-weight: bold; }
.info-table {
  width: 100%;
  border-collapse: collapse;
  margin-bottom: 20px;
}
.info-table td {
  padding: 8px;
  border: 1px solid #ddd;
  vertical-align: top;
}
.info-table td:first-child {
  font-weight: bold;
  background-color: #f8f9fa;
  width: 25%;
}
.patient-info-header { margin-bottom: 15px; }
                .patient-header-table { 
  width: 100%; 
  border-collapse: collapse; 
  font-size: 12pt; 
  margin-bottom: 20px;
}
.patient-header-table td { 
  padding: 4px 8px; 
  border: 1px solid #000; 
  vertical-align: top; 
}
.patient-header-table .label { 
  font-weight: bold; 
  background-color: #f0f0f0; 
  width: 30%; 
}
.patient-header-table .value { 
  background-color: white; 
}
.content-section {
  margin-bottom: 20px;
}
.signature-section {
  margin-top: 40px;
  border-top: 1px solid #ccc;
  padding-top: 20px;
}
</style>
</head>
<body>
${htmlContent.replace(/<html[^>]*>|<\/html>|<head[^>]*>[\s\S]*?<\/head>|<body[^>]*>|<\/body>|<!DOCTYPE[^>]*>/gi, '')}
</body>
</html>`;
        
        // Create blob with proper MIME type for Word
        blob = new Blob([completeHtmlDoc], { 
          type: 'application/msword'
        });
        
        // Change extension to .doc for better compatibility with HTML-based Word documents
        downloadFileName = fileName.replace(/\.(docx?|html?)$/i, '') + '.doc';
      }
      
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = downloadFileName;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);

      toast({
        title: "Success",
        description: "Document downloaded successfully",
      });
    } catch (err) {
      toast({
        title: "Download Error",
        description: "Failed to download the document",
        variant: "destructive",
      });
    }
  };

  return (
    <Card className={`word-document-viewer ${className}`}>
      <CardContent className="p-0">
        <div 
          className="relative border-t"
          style={{ height }}
        >
          {isLoading && (
            <div className="absolute inset-0 flex items-center justify-center bg-white/80 z-10">
              <div className="flex flex-col items-center space-y-2">
                <Loader2 className="w-8 h-8 animate-spin text-blue-600" />
                <p className="text-sm text-gray-600">Loading document...</p>
              </div>
            </div>
          )}
          
          {error && (
            <div className="absolute inset-0 flex items-center justify-center bg-white z-10">
              <div className="flex flex-col items-center space-y-4 p-6 text-center">
                <AlertTriangle className="w-12 h-12 text-red-500" />
                <div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">Failed to Load Document</h3>
                  <p className="text-sm text-gray-600 max-w-md">{error}</p>
                </div>
                <Button
                  variant="outline"
                  onClick={handleDownload}
                  className="flex items-center"
                >
                  <Download className="w-4 h-4 mr-1" />
                  Download Instead
                </Button>
              </div>
            </div>
          )}
          
          <div 
            ref={containerRef}
            className="w-full h-full overflow-auto p-4 bg-white"
            style={{
              minHeight: height,
              fontSize: '14px',
              lineHeight: '1.6'
            }}
          />
        </div>
      </CardContent>
    </Card>
  );
};

export default WordDocumentViewer;

